url: "https://test-stand.gb.ru/gateway/login"
login: "humanist"
password: "ec6c0fbac2"
url_get: "https://test-stand.gb.ru/api/posts"
url_post: "https://test-stand.gb.ru/api/posts?_ga=2.98834590.1031290318.1700754000-1809671657.1700754000"
ttl: "post-test2"